Module MenuItemTexts
    Friend Const AbandonGameText = "Abandon Game"
    Friend Const ContinueText = "Continue"
    Friend Const DanceOffText = "DANCE OFF!!"
    Friend Const GameMenuText = "Game Menu"
    Friend Const GiveUpText = "Give Up!"
    Friend Const MoveText = "Move..."
    Friend Const NeverMindText = "Never Mind"
    Friend Const NoText = "No"
    Friend Const ProfileText = "Profile"
    Friend Const QuitText = "Quit"
    Friend Const SaveText = "Save..."
    Friend Const StartText = "Start"
    Friend Const VisitLifeCoachText = "Visit Life Coach"
    Friend Const YesText = "Yes"
End Module
